// this file is automatically generated by routeGen.mjs
// will automatically (in runtime) create express routes based on the files in the api folder

import { Router } from "express";
import { getSomethingElse } from "../api/somethingElse/route";
import { postSomethingElse } from "../api/somethingElse/route";
import { getTest } from "../api/test/route";
import { getUsers } from "../api/user/route";
import { postUsers } from "../api/user/route";

export default function () {
  const router = Router();
  router.get("/somethingElse", getSomethingElse);
  router.post("/somethingElse", postSomethingElse);
  router.get("/test", getTest);
  router.get("/user", getUsers);
  router.post("/user", postUsers);

  return router;
}
